version: '3.8'

services:
  ico-collector:
    build: .
    container_name: ico-collector-streamlit
    ports:
      - "8501:8501"
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
      - MAX_REQ_PER_MIN=60
      - REQUEST_TIMEOUT=12
      - RETRY_COUNT=3
      - MAX_WORKERS=6
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./logs:/app/logs:rw
      - ./uploads:/app/uploads:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - ico-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: ico-collector-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - ico-collector
    restart: unless-stopped
    networks:
      - ico-network
    profiles:
      - production

  # Optional: Redis for session storage
  redis:
    image: redis:7-alpine
    container_name: ico-collector-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ico-network
    profiles:
      - production

networks:
  ico-network:
    driver: bridge

volumes:
  redis_data: